/homes/dcaputo/.local/lib/python3.9/site-packages/torch/distributed/launch.py:181: FutureWarning: The module torch.distributed.launch is deprecated
and will be removed in future. Use torchrun.
Note that --use-env is set by default in torchrun.
If your script expects `--local-rank` argument to be set, please
change it to read from `os.environ['LOCAL_RANK']` instead. See 
https://pytorch.org/docs/stable/distributed.html#launch-utility for 
further instructions

  warnings.warn(
WARNING:torch.distributed.run:
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
*****************************************
Traceback (most recent call last):
  File "/homes/dcaputo/GX_alBERTo/train_ddp.py", line 1, in <module>
    from src.dataset import train_dataloader, val_dataloader, which_dataset
  File "/homes/dcaputo/GX_alBERTo/src/dataset.py", line 34, in <module>
    df0 = pd.read_hdf('dataset/Dataset/df_alBERTo_0.h5', key='1234', mode='r')
  File "/usr/local/anaconda3/lib/python3.9/site-packages/pandas/io/pytables.py", line 455, in read_hdf
    return store.select(
  File "/usr/local/anaconda3/lib/python3.9/site-packages/pandas/io/pytables.py", line 875, in select
    return it.get_result()
  File "/usr/local/anaconda3/lib/python3.9/site-packages/pandas/io/pytables.py", line 1943, in get_result
    results = self.func(self.start, self.stop, where)
  File "/usr/local/anaconda3/lib/python3.9/site-packages/pandas/io/pytables.py", line 859, in func
    return s.read(start=_start, stop=_stop, where=_where, columns=columns)
  File "/usr/local/anaconda3/lib/python3.9/site-packages/pandas/io/pytables.py", line 3206, in read
    values = self.read_array(f"block{i}_values", start=_start, stop=_stop)
  File "/usr/local/anaconda3/lib/python3.9/site-packages/pandas/io/pytables.py", line 2871, in read_array
    ret = node[0][start:stop]
  File "/usr/local/anaconda3/lib/python3.9/site-packages/tables/vlarray.py", line 677, in __getitem__
    return self.read(start, stop, step)[0]
  File "/usr/local/anaconda3/lib/python3.9/site-packages/tables/vlarray.py", line 821, in read
    outlistarr = [atom.fromarray(arr) for arr in listarr]
  File "/usr/local/anaconda3/lib/python3.9/site-packages/tables/vlarray.py", line 821, in <listcomp>
    outlistarr = [atom.fromarray(arr) for arr in listarr]
  File "/usr/local/anaconda3/lib/python3.9/site-packages/tables/atom.py", line 1224, in fromarray
    return pickle.loads(array.tostring())
AttributeError: Can't get attribute 'csr_array' on <module 'scipy.sparse._csr' from '/usr/local/anaconda3/lib/python3.9/site-packages/scipy/sparse/_csr.py'>
Closing remaining open files:dataset/Dataset/df_alBERTo_0.h5...Traceback (most recent call last):
  File "/homes/dcaputo/GX_alBERTo/train_ddp.py", line 1, in <module>
    from src.dataset import train_dataloader, val_dataloader, which_dataset
  File "/homes/dcaputo/GX_alBERTo/src/dataset.py", line 34, in <module>
    df0 = pd.read_hdf('dataset/Dataset/df_alBERTo_0.h5', key='1234', mode='r')
  File "/usr/local/anaconda3/lib/python3.9/site-packages/pandas/io/pytables.py", line 455, in read_hdf
    return store.select(
  File "/usr/local/anaconda3/lib/python3.9/site-packages/pandas/io/pytables.py", line 875, in select
    return it.get_result()
  File "/usr/local/anaconda3/lib/python3.9/site-packages/pandas/io/pytables.py", line 1943, in get_result
    results = self.func(self.start, self.stop, where)
  File "/usr/local/anaconda3/lib/python3.9/site-packages/pandas/io/pytables.py", line 859, in func
    return s.read(start=_start, stop=_stop, where=_where, columns=columns)
  File "/usr/local/anaconda3/lib/python3.9/site-packages/pandas/io/pytables.py", line 3206, in read
    values = self.read_array(f"block{i}_values", start=_start, stop=_stop)
  File "/usr/local/anaconda3/lib/python3.9/site-packages/pandas/io/pytables.py", line 2871, in read_array
    ret = node[0][start:stop]
  File "/usr/local/anaconda3/lib/python3.9/site-packages/tables/vlarray.py", line 677, in __getitem__
    return self.read(start, stop, step)[0]
  File "/usr/local/anaconda3/lib/python3.9/site-packages/tables/vlarray.py", line 821, in read
    outlistarr = [atom.fromarray(arr) for arr in listarr]
  File "/usr/local/anaconda3/lib/python3.9/site-packages/tables/vlarray.py", line 821, in <listcomp>
    outlistarr = [atom.fromarray(arr) for arr in listarr]
  File "/usr/local/anaconda3/lib/python3.9/site-packages/tables/atom.py", line 1224, in fromarray
    return pickle.loads(array.tostring())
AttributeError: Can't get attribute 'csr_array' on <module 'scipy.sparse._csr' from '/usr/local/anaconda3/lib/python3.9/site-packages/scipy/sparse/_csr.py'>
Closing remaining open files:dataset/Dataset/df_alBERTo_0.h5...done
done
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 1298584) of binary: /usr/local/anaconda3/bin/python
Traceback (most recent call last):
  File "/usr/local/anaconda3/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/anaconda3/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/homes/dcaputo/.local/lib/python3.9/site-packages/torch/distributed/launch.py", line 196, in <module>
    main()
  File "/homes/dcaputo/.local/lib/python3.9/site-packages/torch/distributed/launch.py", line 192, in main
    launch(args)
  File "/homes/dcaputo/.local/lib/python3.9/site-packages/torch/distributed/launch.py", line 177, in launch
    run(args)
  File "/homes/dcaputo/.local/lib/python3.9/site-packages/torch/distributed/run.py", line 785, in run
    elastic_launch(
  File "/homes/dcaputo/.local/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/homes/dcaputo/.local/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 250, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
train_ddp.py FAILED
------------------------------------------------------------
Failures:
[1]:
  time      : 2024-03-26_19:12:08
  host      : nullazzo.ing.unimo.it
  rank      : 1 (local_rank: 1)
  exitcode  : 1 (pid: 1298585)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-03-26_19:12:08
  host      : nullazzo.ing.unimo.it
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 1298584)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
